version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/maga_hotel
      - SPRING_DATASOURCE_USERNAME=zhengchy
      - SPRING_DATASOURCE_PASSWORD=java_9053
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maga_hotel
      - POSTGRES_USER=zhengchy
      - POSTGRES_PASSWORD=java_9053
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
      
volumes:
  dbdata:
